# Script to Despin the spacecraft

cmd("ADCS SET_TARGET_ANG_V with CCSDS_STREAMID 6544, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 25, CCSDS_FUNCCODE 4, CCSDS_CHECKSUM 0, WX 0, WY 0, WZ 0")
cmd("ADCS ALGO_SELECT with CCSDS_STREAMID 6544, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, EST_ALGO 1, CTRL_ALGO 0")