# For this solver we are going to use the MEMS_ONLY estimator so the sun will be at 
# qx=0, qy=0, qz=0, qw=1
cmd("ADCS SET_TARGET_QUATERNION with CCSDS_STREAMID 6544, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 33, CCSDS_FUNCCODE 6, CCSDS_CHECKSUM 0, QX 0, QY 0, QZ 0, QS 1")
cmd("ADCS ALGO_SELECT with CCSDS_STREAMID 6544, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, EST_ALGO 1, CTRL_ALGO 1")
# we're also going to turn off gps and star tracker to save power
# gps off
cmd("EPS DEVICE_POWER with CCSDS_STREAMID 6546, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, DEVICE 2, STATE 0")
# star tracker off
cmd("EPS DEVICE_POWER with CCSDS_STREAMID 6546, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, DEVICE 4, STATE 0")
# Make sure the three mems devices are on
# css on
cmd("EPS DEVICE_POWER with CCSDS_STREAMID 6546, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, DEVICE 0, STATE 1")
# imu on
cmd("EPS DEVICE_POWER with CCSDS_STREAMID 6546, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, DEVICE 1, STATE 1")
# magnetometer on
cmd("EPS DEVICE_POWER with CCSDS_STREAMID 6546, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 3, CCSDS_FUNCCODE 2, CCSDS_CHECKSUM 0, DEVICE 3, STATE 1")